#!/bin/bash
# Compile java files
find src -name '*.java' -not -name 'PlanViewer.java' > sources.txt
javac @sources.txt
rm sources.txt

# Run acquisition planner
echo "-------- Running acquition planner ------"
java -cp bin solver.BadAcquisitionPlanner

# Run acquisition optimisation
if hash oplrun 2>/dev/null; then
    export LD_LIBRARY_PATH=~/apps/cplex/opl/bin/x86-64_linux/
    OPL=oplrun
else
    module load ilog/12.7
    OPL=/usr/local/ilog-12.7/opl/bin/x86-64_linux/oplrun
fi

# Run acq optimisation
echo "-------- Running acquition optimisation ------"
cd output
$OPL acqPlanning.mod acqPlanning_SAT1.dat
$OPL acqPlanning.mod acqPlanning_SAT2.dat
cd ..

java -cp bin solver.MagnificentDownloadPlanner
